import Mock from 'mockjs';
var small_list = Mock.mock('http://small_list.cn',[
	{
		"id":"@id",
        "title":'团结·智慧·勇气——习近平主席主持中非合作论坛北京峰会',
        "timelong":30,
        "comment":63,
        "media":"新华网",
        "type":"国际",
        "small_img":'https://p2.pstatp.com/large/3658/7378365093'
	},
	{
		"id":"@id",
        "title":'习近平会见摩洛哥首相奥斯曼尼',
        "timelong":21,
        "comment":45,
        "media":"新华网",
        "type":"国际",
        "small_img":'https://p2.pstatp.com/large/3658/7378365093'
	},
	{
		"id":"@id",
        "title":'太多人酒后猝死！酒后爱做3件事，基本很难躲过',
        "timelong":32,
        "comment":15,
        "media":"人民网",
        "type":"健康",
        "small_img":'https://p3.pstatp.com/large/ca400072481685ad43b'
	},
	{
		"id":"@id",
        "title":'吉林榆树市副市长疑从6楼坠下 医院称已转往长春治疗｜沸点',
        "timelong":21,
        "comment":45,
        "media":"新京报",
        "type":"社会",
        "small_img":'https://p1.pstatp.com/large/8532/7581013616'
	},
])
var content_list = Mock.mock('http://content_list.cn',[
	{
		"id":"@id",
        "title":'阿联酋飞美国航班上19人染病 乘客：早觉得不对劲',
        "timelong":30,
        "comment":63,
        "media":"新华网",
        "type":"国际",
        "small_img":'https://p2.pstatp.com/large/3658/7378365093',
	},
	{
		"id":"@id",
        "title":'油品升级，92号汽油将退出历史舞台，加油站偷笑，车主却欲哭无',
        "timelong":21,
        "comment":45,
        "media":"新华网",
        "type":"国际",
         "small_img":'https://p2.pstatp.com/large/3658/7378365093',
	},
	{
		"id":"@id",
        "title":'让你的送货单管理更加简单、高效、智能',
        "timelong":31,
        "comment":25,
        "media":"上海精圆",
        "type":"广告",
        "small_img":'https://p2.pstatp.com/large/3658/7378365093',
	},
	{
		"id":"@id",
        "title":'我领馆接走被困台胞却被绿媒抹黑 台网友：我们本就是中国人',
        "timelong":32,
        "comment":15,
        "media":"人民网",
        "type":"健康",
        "small_img":'https://p3.pstatp.com/large/ca400072481685ad43b',
	},
	{
		"id":"@id",
        "title":'小面馆都注册商标了！快查查你的品牌是否被抢注',
        "timelong":21,
        "comment":45,
        "media":"新京报",
        "type":"社会",
         "small_img":'https://p1.pstatp.com/large/8532/7581013616',
	},
	
])
var text_img_list = Mock.mock('http://text_img_list.cn',[
	{
		"id":"@id",
        "title":'6岁男孩独自照顾瘫痪妈妈，累倒住院，病愈',
        "num":3
	},
	{
		"id":"@id",
        "title":'阿拉伯国家也闹“气荒”？民众排队灌液化气，背后原因引人深思',
        "num":6
	},
	{
		"id":"@id",
        "title":'屹立在长江江心700年的房子，到底有什么秘密',
        "num":4
	},
	{
		"id":"@id",
        "title":'6岁男孩独自照顾瘫痪妈妈，累倒住院，病愈',
        "num":5
	},
	{
		"id":"@id",
        "title":'阿拉伯国家也闹“气荒”？民众排队灌液化气，背后原因引人深思',
        "num":7
	},
	{
		"id":"@id",
        "title":'屹立在长江江心700年的房子，到底有什么秘密',
        "num":6
	},
	
])
var hotnew = Mock.mock('http://hotnew.cn',[
	{
		"id":"@id",
        "title":'蔡英文不管滞日台胞 日语发推称“帮日本渡难关',
        "num":3
	},
	{
		"id":"@id",
        "title":'阿拉伯国家也闹“气荒”？民众排队灌液化气，背后原因引人深思',
        "num":6
	},
	{
		"id":"@id",
        "title":'洪灾背后，是一直被缺水折磨的寿光',
        "num":4
	},
	{
		"id":"@id",
        "title":'刘强东美国律师和警方检方协商撤案？警方：调查仍在进行中',
        "num":5
	},
	
])
var moreList = Mock.mock('http://moreList.cn',[
      {
        "text":"关于头条",
        "link":"https://www.toutiao.com/about/"
      },
      {
        "text":"加入头条",
        "link":"https://job.bytedance.com/campus/position"
      },
      {
        "text":"媒体报道",
        "link":"https://www.toutiao.com/report/"
      },
      {
        "text":"媒体合作",
        "link":"https://www.toutiao.com/media_partners/"
      },
      {
        "text":"产品合作",
        "link":"https://www.toutiao.com/cooperation/"
      },
      {
        "text":"合作说明",
        "link":"https://www.toutiao.com/media_cooperation/"
      },
      {
        "text":"广告投放",
        "link":"https://ad.toutiao.com/promotion/?source2=pchomemore"
      },
      {
        "text":"联系我们",
        "link":"https://www.toutiao.com/contact/"
      },
      {
        "text":"用户协议",
        "link":"https://www.toutiao.com/user_agreement/"
      },
      {
        "text":"隐私政策",
        "link":"https://www.toutiao.com/privacy_protection/"
      },
      {
        "text":"侵权投诉",
        "link":"https://www.toutiao.com/complain/"
      },
      {
        "text":"廉洁举报",
        "link":"https://www.toutiao.com/corrupt_report/"
      },
      {
        "text":"企业认证",
        "link":"https://sso.toutiao.com/login/?service=https%3A%2F%2Frenzheng.toutiao.com%2Fguide%3Fplatform%3D%27PC%27%26source%3D%27www.toutiao.com%27"
      },
     
])
var sun_content_list = Mock.mock('http://sun_content_list.cn',[
	{
		"id":"@id",
        "title":'颈椎疼痛不忙，扭一扭拉拉筋，颈椎不适松解疼痛一天比一天好',
        "timelong":30,
        "comment":63,
        "media":"新华网",
        "type":"国际",
        "small_img":'https://p3.pstatp.com/large/6ee900049dfaa05a3acd',
	},
	{
		"id":"@id",
        "title":'超级飞侠：乐迪拿着球跳探戈，结果摔倒在地球被胡丽塔接住！',
        "timelong":21,
        "comment":45,
        "media":"新华网",
        "type":"国际",
         "small_img":'https://p1.pstatp.com/large/6ee8000148b9a2cddde0',
	},
	{
		"id":"@id",
        "title":'师徒合跳44步鬼步舞，第一次发现鬼步舞可以跳的这么整齐好看',
        "timelong":32,
        "comment":15,
        "media":"人民网",
        "type":"健康",
        "small_img":'https://p3.pstatp.com/large/2c5d0007a93a1801aa73',
	},
	{
		"id":"@id",
        "title":'让你的送货单管理更加简单、高效、智能',
        "timelong":31,
        "comment":25,
        "media":"上海精圆",
        "type":"广告",
        "small_img":'https://p2.pstatp.com/large/3658/7378365093',
	},
	{
		"id":"@id",
        "title":'一件藏品竟引发过家庭矛盾，现在带来鉴宝，这结果也是值了！',
        "timelong":21,
        "comment":45,
        "media":"新京报",
        "type":"社会",
         "small_img":'https://p1.pstatp.com/large/3592/4134968376',
	},
	{
		"id":"@id",
        "title":'颈椎疼痛不忙，扭一扭拉拉筋，颈椎不适松解疼痛一天比一天好',
        "timelong":30,
        "comment":63,
        "media":"新华网",
        "type":"国际",
        "small_img":'https://p3.pstatp.com/large/6ee900049dfaa05a3acd',
	},
	{
		"id":"@id",
        "title":'超级飞侠：乐迪拿着球跳探戈，结果摔倒在地球被胡丽塔接住！',
        "timelong":21,
        "comment":45,
        "media":"新华网",
        "type":"国际",
         "small_img":'https://p1.pstatp.com/large/6ee8000148b9a2cddde0',
	},
	{
		"id":"@id",
        "title":'师徒合跳44步鬼步舞，第一次发现鬼步舞可以跳的这么整齐好看',
        "timelong":32,
        "comment":15,
        "media":"人民网",
        "type":"健康",
        "small_img":'https://p3.pstatp.com/large/2c5d0007a93a1801aa73',
	},
	{
		"id":"@id",
        "title":'一件藏品竟引发过家庭矛盾，现在带来鉴宝，这结果也是值了！',
        "timelong":21,
        "comment":45,
        "media":"新京报",
        "type":"社会",
         "small_img":'https://p1.pstatp.com/large/3592/4134968376',
	},
	{
		"id":"@id",
        "title":'让你的送货单管理更加简单、高效、智能',
        "timelong":31,
        "comment":25,
        "media":"上海精圆",
        "type":"广告",
        "small_img":'https://p2.pstatp.com/large/3658/7378365093',
	},
	{
		"id":"@id",
        "title":'颈椎疼痛不忙，扭一扭拉拉筋，颈椎不适松解疼痛一天比一天好',
        "timelong":30,
        "comment":63,
        "media":"新华网",
        "type":"国际",
        "small_img":'https://p3.pstatp.com/large/6ee900049dfaa05a3acd',
	},
	{
		"id":"@id",
        "title":'超级飞侠：乐迪拿着球跳探戈，结果摔倒在地球被胡丽塔接住！',
        "timelong":21,
        "comment":45,
        "media":"新华网",
        "type":"国际",
         "small_img":'https://p1.pstatp.com/large/6ee8000148b9a2cddde0',
	},
	{
		"id":"@id",
        "title":'师徒合跳44步鬼步舞，第一次发现鬼步舞可以跳的这么整齐好看',
        "timelong":32,
        "comment":15,
        "media":"人民网",
        "type":"健康",
        "small_img":'https://p3.pstatp.com/large/2c5d0007a93a1801aa73',
	},
	{
		"id":"@id",
        "title":'一件藏品竟引发过家庭矛盾，现在带来鉴宝，这结果也是值了！',
        "timelong":21,
        "comment":45,
        "media":"新京报",
        "type":"社会",
         "small_img":'https://p1.pstatp.com/large/3592/4134968376',
	},
	
])
export default {
	small_list,
	content_list,
	text_img_list,
	moreList,
	sun_content_list,
}

